rework bindings and prepare for deployer/local testing tool

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -32,3 +32,15 @@ jobs:
       - uses: actions/checkout@v4
       - uses: asdf-vm/actions/install@v3.0.2
       - run: scarb test --all-features
+
+  rust_bindings:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions-rs/toolchain@v1
+      - uses: asdf-vm/actions/install@v3.0.2
+      - name: Generate bindings
+        run: bash scripts/generate_bindings.sh
+      - name: Check for changes
+        run: |
+          git diff --exit-code || (echo "Error: Generated bindings are not up to date. Please run 'bash scripts/generate_bindings.sh' and commit the changes." && exit 1)
